package org.octavio.paymentreconciliationsim.http;

import io.swagger.v3.oas.annotations.media.Schema;

/** Stable sanitized HTTP error; request identifiers are generated by the server. */
public record ApiError(
        @Schema(requiredMode=Schema.RequiredMode.REQUIRED) String code,
        @Schema(requiredMode=Schema.RequiredMode.REQUIRED) String message,
        @Schema(requiredMode=Schema.RequiredMode.REQUIRED, format="uuid") String correlationId) {}
